# Generated by Django 4.2.7 on 2024-02-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedProductsList',
            fields=[
                ('graph_id', models.BigIntegerField(blank=True, db_column='Graph_id', null=True)),
                ('product_id', models.CharField(blank=True, db_column='Product_id', null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('invoice_id', models.CharField(blank=True, db_column='Invoice_id', null=True)),
                ('inc_prod_list', models.BigAutoField(db_column='Inc_prod_list', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Included_products_list',
            },
        ),
        migrations.AddField(
            model_name='kugraph',
            name='sum_approved',
            field=models.FloatField(blank=True, db_column='Sum_approved', null=True),
        ),
    ]
