# Generated by Django 4.2.7 on 2023-12-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('name', models.CharField(blank=True, null=True)),
                ('id', models.CharField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, db_column='Product_Id', null=True)),
                ('vendor_id', models.CharField(blank=True, db_column='Vendor_Id', null=True)),
                ('entity_id', models.CharField(blank=True, db_column='Entity_Id', null=True)),
            ],
            options={
                'db_table': 'Assortment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('entityid', models.CharField(db_column='EntityId', max_length=4, primary_key=True, serialize=False)),
                ('directorname', models.CharField(blank=True, db_column='DirectorName', max_length=100, null=True)),
                ('urasticname', models.CharField(db_column='UrasticName', max_length=100)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('urasticaddress', models.CharField(blank=True, db_column='UrasticAddress', max_length=250, null=True)),
                ('inn_kpp', models.CharField(blank=True, db_column='INN\\KPP', max_length=121, null=True)),
                ('bankname', models.CharField(db_column='BankName', max_length=100)),
                ('account', models.CharField(db_column='Account', max_length=35)),
                ('corraccount', models.CharField(db_column='CorrAccount', max_length=35)),
                ('bankbink', models.CharField(db_column='BankBink', max_length=15)),
                ('mergeid', models.CharField(blank=True, db_column='MergeID', max_length=4, null=True)),
            ],
            options={
                'db_table': 'Entities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.BigIntegerField(db_column='Invoice_id', primary_key=True, serialize=False)),
                ('vendor_id', models.CharField(db_column='Vendor_id', max_length=20)),
                ('doc_id', models.CharField(db_column='Doc_id', max_length=70)),
                ('entity_id', models.CharField(db_column='Entity_id', max_length=4)),
                ('invoice_name', models.CharField(db_column='Invoice_name', max_length=100)),
                ('invoice_number', models.CharField(db_column='Invoice_number', max_length=100)),
                ('date', models.DateField(db_column='Date')),
                ('purch_number', models.CharField(db_column='Purch_number', max_length=100)),
                ('purch_date', models.DateField(db_column='Purch_date')),
                ('doc_type', models.IntegerField(db_column='Doc_type')),
                ('invoices_status', models.IntegerField(db_column='Invoices_status')),
                ('on_off', models.TextField(blank=True, db_column='On_off', null=True)),
                ('base', models.TextField(blank=True, db_column='Base', null=True)),
                ('exclude_return', models.TextField(blank=True, db_column='Exclude_return', null=True)),
                ('ofactured', models.TextField(blank=True, db_column='Ofactured', null=True)),
                ('ku_type', models.CharField(blank=True, db_column='KU_type', max_length=50, null=True)),
                ('pay_type', models.CharField(blank=True, db_column='Pay_type', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ku',
            fields=[
                ('ku_id', models.BigIntegerField(db_column='KU_id', primary_key=True, serialize=False)),
                ('period', models.CharField(db_column='Period', max_length=10)),
                ('date_start', models.DateField(db_column='Date_start')),
                ('date_end', models.DateField(blank=True, db_column='Date_end', null=True)),
                ('status', models.CharField(db_column='Status', max_length=20)),
            ],
            options={
                'db_table': 'KU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KuGraph',
            fields=[
                ('graph_id', models.BigIntegerField(db_column='Graph_id', primary_key=True, serialize=False)),
                ('vendor_id', models.BigIntegerField(db_column='Vendor_id')),
                ('period', models.CharField(db_column='Period', max_length=10)),
                ('date_start', models.DateField(db_column='Date_start')),
                ('date_end', models.DateField(db_column='Date_end')),
                ('date_calc', models.DateField(db_column='Date_calc')),
                ('status', models.CharField(db_column='Status', max_length=2)),
                ('sum_calc', models.FloatField(blank=True, db_column='Sum_calc', null=True)),
                ('sum_bonus', models.FloatField(blank=True, db_column='Sum_bonus', null=True)),
                ('percent', models.IntegerField(blank=True, db_column='Percent', null=True)),
            ],
            options={
                'db_table': 'KU_graph',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('itemid', models.CharField(db_column='itemId', primary_key=True, serialize=False)),
                ('classifier_id', models.CharField(blank=True, db_column='Classifier_id', null=True)),
                ('brand_id', models.CharField(blank=True, db_column='Brand_id', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test', models.CharField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('entityid', models.CharField(blank=True, db_column='EntityID', max_length=4, null=True)),
                ('vendorid', models.CharField(db_column='VendorId', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('urasticname', models.CharField(blank=True, db_column='UrasticName', max_length=100, null=True)),
                ('inn_kpp', models.CharField(blank=True, db_column='INN/KPP', max_length=121, null=True)),
                ('directorname', models.CharField(blank=True, db_column='DirectorName', max_length=100, null=True)),
                ('urasticadress', models.CharField(blank=True, db_column='UrasticAdress', max_length=250, null=True)),
                ('account', models.CharField(blank=True, db_column='Account', max_length=35, null=True)),
                ('bankname', models.CharField(blank=True, db_column='BankName', max_length=100, null=True)),
                ('bankbik', models.CharField(blank=True, db_column='BankBik', max_length=15, null=True)),
                ('corraccount', models.CharField(blank=True, db_column='CorrAccount', max_length=35, null=True)),
                ('dirparty', models.BigIntegerField(blank=True, db_column='DirParty', null=True)),
            ],
            options={
                'db_table': 'Vendors',
                'managed': False,
            },
        ),
    ]
