# Generated by Django 4.2.7 on 2023-12-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brandclassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifierid', models.CharField(db_column='ClassifierID')),
                ('brand_name', models.CharField(db_column='Brand_name')),
                ('producer_name', models.CharField(db_column='Producer_name')),
            ],
            options={
                'db_table': 'BrandClassifier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifierid', models.CharField(db_column='ClassifierID')),
                ('l1', models.CharField(db_column='L1')),
                ('l1_name', models.CharField(db_column='L1_name')),
                ('l2', models.CharField(db_column='L2')),
                ('l2_name', models.CharField(db_column='L2_name')),
                ('l3', models.CharField(db_column='L3')),
                ('l3_name', models.CharField(db_column='L3_name')),
                ('l4', models.CharField(db_column='L4')),
                ('l4_name', models.CharField(db_column='L4_name')),
            ],
            options={
                'db_table': 'Classifier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venddoc',
            fields=[
                ('vendor_id', models.CharField(db_column='Vendor_id')),
                ('entity_id', models.CharField(db_column='Entity_id')),
                ('docid', models.CharField(blank=True, db_column='DocID', null=True)),
                ('doctype', models.CharField(db_column='DocType')),
                ('invoice_name', models.CharField(db_column='Invoice_name')),
                ('invoice_number', models.CharField(db_column='Invoice_number')),
                ('invoice_date', models.DateField(db_column='Invoice_date')),
                ('purch_number', models.CharField(db_column='Purch_number')),
                ('purch_date', models.DateField(db_column='Purch_date')),
                ('invoicestatus', models.CharField(blank=True, db_column='InvoiceStatus', null=True)),
                ('invoice_id', models.BigAutoField(db_column='Invoice_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'VendDoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venddoclines',
            fields=[
                ('recid', models.BigIntegerField(db_column='RecId', primary_key=True, serialize=False)),
                ('docid', models.CharField(blank=True, db_column='DocID', null=True)),
                ('product_id', models.CharField(db_column='Product_id')),
                ('qty', models.FloatField(db_column='QTY')),
                ('amount', models.FloatField(db_column='Amount')),
                ('amountvat', models.FloatField(db_column='AmountVAT')),
                ('vat', models.FloatField(db_column='VAT')),
            ],
            options={
                'db_table': 'VendDocLines',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
