# Generated by Django 4.2.7 on 2024-01-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0002_authtokentoken_brandclassifier_classifier_venddoc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ku',
            options={'managed': True},
        ),
    ]
