# Generated by Django 4.2.7 on 2024-01-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0003_alter_ku_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ku',
            options={'managed': False},
        ),
    ]
