# Generated by Django 4.2.7 on 2024-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0004_alter_ku_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier_code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('parent_code', models.CharField(max_length=12)),
            ],
        ),
    ]
