# Generated by Django 4.2.7 on 2024-02-15 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0005_classifiertest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifiertest',
            options={'managed': False},
        ),
    ]
