# Generated by Django 4.2.7 on 2024-02-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAMA_ucup', '0006_alter_classifiertest_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classifiertest',
            table='app_classifier',
        ),
    ]
